package securenotepad;    
import ioProcesses.*;
import javax.swing.JFileChooser;
import rsa.*;

public class NotepadInterface extends javax.swing.JFrame {
    public static String message;
    
    public NotepadInterface() {
        
        initComponents();
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_title_write = new javax.swing.JLabel();
        encrypt_button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tp_text = new javax.swing.JTextPane();
        info_label = new javax.swing.JLabel();
        label_read = new javax.swing.JLabel();
        label_write = new javax.swing.JLabel();
        tf_input_read = new javax.swing.JLabel();
        tf_title_write = new javax.swing.JTextField();
        info_label_read = new javax.swing.JLabel();
        filechooser = new javax.swing.JFileChooser();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Secure Notepad");
        setBackground(new java.awt.Color(0, 0, 0));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_title_write.setText("Bir Başlık Ekle :");
        getContentPane().add(label_title_write, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 88, 28));

        encrypt_button.setText("Şifrele");
        encrypt_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encrypt_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(encrypt_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 460, 90, 30));

        tp_text.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jScrollPane1.setViewportView(tp_text);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 430, 368));

        info_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(info_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 150, 30));

        label_read.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        label_read.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_read.setText("NOT OKU");
        getContentPane().add(label_read, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 460, 50));

        label_write.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        label_write.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_write.setText("NOT YAZ");
        getContentPane().add(label_write, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 430, 50));

        tf_input_read.setText("Okumak İstediğiniz Şifreli Notu Seçiniz");
        getContentPane().add(tf_input_read, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, 243, 28));

        tf_title_write.setOpaque(true);
        tf_title_write.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_title_writeActionPerformed(evt);
            }
        });
        getContentPane().add(tf_title_write, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 330, 30));
        getContentPane().add(info_label_read, new org.netbeans.lib.awtextra.AbsoluteConstraints(665, 467, 310, 22));

        filechooser.setDialogType(javax.swing.JFileChooser.CUSTOM_DIALOG);
        filechooser.setApproveButtonText("Şifreyi Çöz");
        filechooser.setDialogTitle("Okumak İstediğiniz Şifreli Notu Seçiniz");
        filechooser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        filechooser.setDragEnabled(true);
        filechooser.setOpaque(true);
        filechooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filechooserActionPerformed(evt);
            }
        });
        getContentPane().add(filechooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 470, 350));

        background.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void encrypt_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encrypt_buttonActionPerformed
        String fileName=tf_title_write.getText();
        String text=tp_text.getText();
        TextChiper tc = new TextChiper(new Rsa(1));
        ioProcesses io = new ioProcesses();
        io.writeFile(fileName, tc.encryptText(text));
        info_label.setText("İşlem Başarılı...");
        tf_title_write.setText("");
        tp_text.setText("");

        
    }//GEN-LAST:event_encrypt_buttonActionPerformed

    private void tf_title_writeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_title_writeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_title_writeActionPerformed

    private void filechooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filechooserActionPerformed
        if (evt.getActionCommand().equals(JFileChooser.APPROVE_SELECTION)) {
            this.message="";
            TextChiper tc = new TextChiper(new Rsa(1));
            ioProcesses io = new ioProcesses();
            String chiperText=io.readFile(filechooser.getSelectedFile());
            this.message =tc.decryptText(chiperText);
            ShowMessage sm = new ShowMessage();

        }
    }//GEN-LAST:event_filechooserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NotepadInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NotepadInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NotepadInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NotepadInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NotepadInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton encrypt_button;
    private javax.swing.JFileChooser filechooser;
    private javax.swing.JLabel info_label;
    private javax.swing.JLabel info_label_read;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_read;
    private javax.swing.JLabel label_title_write;
    private javax.swing.JLabel label_write;
    private javax.swing.JLabel tf_input_read;
    private javax.swing.JTextField tf_title_write;
    private javax.swing.JTextPane tp_text;
    // End of variables declaration//GEN-END:variables
}
